/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "microdatabase_constants.h"

namespace microdatabase {

const microdatabaseConstants g_microdatabase_constants;

microdatabaseConstants::microdatabaseConstants() {
}

} // namespace

