/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef microdatabase_CONSTANTS_H
#define microdatabase_CONSTANTS_H

#include "microdatabase_types.h"

namespace microdatabase {

class microdatabaseConstants {
 public:
  microdatabaseConstants();

};

extern const microdatabaseConstants g_microdatabase_constants;

} // namespace

#endif
